### ISSUE TITLE
Update E/R Diagram

### ISSUE THREAD

**Issue by samantha-kerr** [samantha-kerr/COMP353-MainProject#1]
Update the E/R  with the following changes:
- [x]  Remove indication of weak entity/relationship between Account and Transaction
- [x]  Add "additional_charge" attribute to ChargePlan
- [x] Add "level" attribute to Account
- [x]  Add an IS-A relationship between different account types and the main Account model. That means creating a separate model for: Saving Checking, CreditCard, Loan, ForeignCurrency.
  - [x] Add CreditCard model with attributes: lim, minimum_payment
  - [x] Add Saving model with attributes:  option (moved from Account)
  - [x] Add Checking model with attributes:  option (moved form Account)
  - [x] Add ForeignCurrency model with attributes: currency_type
  - [x] Add Loan model with attributes: type, lim
- [x] Change Employee model, add attributes: sick_days, payroll, holidays
  - [x] Add Schedule model: (Weak entity) employee_id , day, start_time, end_time. 
- [x] Figure out Interest Rate relation to accounts. 
- [x] Add password attribute to Client. 

Assumptions:
- Line of credit does not become a loan after a certain amount of time. 
- Mortgage, Loan, and Line of Credit are all types of Loan
- No limit for sick days and holidays, only a attribute of what they have taken. 
- Assume salary is yearly, payroll is monthly.

**Comment by jaslatendresse** [comment]
This is the ER so far. What's in red is what is subject to change (InterestRate and bill attribute from entity Credit) 

Question: What is the option attribute on Checking and Savings? And what do we mean by "moved from Account? "option" attribute was not in account, it was in ChargePlan...Should we move it to Checking and Savings? 

![comp353_er-main](https://user-images.githubusercontent.com/17911957/47607750-0260a000-d9f2-11e8-9741-d1d342a146e7.jpg)

**Comment by samantha-kerr** [comment]
Option is a foreign key to ChargePlan option, it was an attribute in Account, but now will be moved to Saving and Checking

**Comment by jaslatendresse** [comment]
So then, should Savings and Checking be weak? From my point on view, I don't think so since they already have the Pkey inherited from Account....

**Comment by samantha-kerr** [comment]
I don’t think I understand your question.. they would not be weak, they’re inherited. The reference/relationship to ChargePlan is just being moved from Account to both Saving and Checking

**Comment by jaslatendresse** [comment]
just wanted to validate what I thought!

**Comment by jaslatendresse** [comment]
@samantha-kerr @RemusCM @CrispiChicken shouldn't payroll be in branch since a payroll is a list of all the employees with their salaries? I just wanna make sure because after we're settled with this i can start with issue #10

**Comment by RemusCM** [comment]
You may be right. When we met, we all thought it was just the salary per month. (cause in the project document, it says "Keep track of all of its employees’ information including their schedule, payroll,
holidays, sick days, etc. (Note: all employees are monthly paid).")

But if we look up for definitions, there are multiple different interpretations such as the one you said, or the total amount that the branch pays all of its employees. So, if we go with definitions, we can certainly put it into branch.

**Comment by jaslatendresse** [comment]
After discussing with @RemusCM we think that payroll shouldn't be in the E/R since it can be obtained by getting the employee_id and the salary. If we put it as an attribute of Branch, the type would have to be an array, which would make our diagram not 3NF. If we put it as an entity itself, it would just store employee_id and salary as FK which would just be duplicating data in a table for now reason.

**Comment by jaslatendresse** [comment]
"For example, no one will get a credit card unless
he/she maintains a satisfactorily level of banking transactions for at least six months, and
no one will get a line of credit before one year."

Assumptions: 
*A client can get a credit card if he has been a client for at least 6 months. A client can get a line of credit if he has been a client for at least a year regardless of the transactions made by the client.

**Comment by jaslatendresse** [comment]
Changes brought to ER:
* Interest rate is an attribute of Account
* payroll is removed from the ER
* Client has a new attribute is_notified of type BIT so they can choose if they want to receive alerts
* New entity created for Bills
* bill attribute is removed from credit card entity

![comp353_er-main-final](https://user-images.githubusercontent.com/17911957/48080627-165b8d00-e1bc-11e8-804d-ed34c3dd9218.jpg)

(Link to diagram)[https://www.draw.io/?state=%7B%22ids%22%3A%5B%221w5MWdG0uwc86WKI0GP_gTzqzoUqBhQKT%22%5D%2C%22action%22%3A%22open%22%2C%22userId%22%3A%22102099128565130865536%22%7D&fbclid=IwAR2wWS_u1rR4oVX8BMUCossjiOXUonTmdlLwFOS1w45mD8RRhZF1fEzdG9A#G1bdm2H3MHdN_sTQOBz6ehNCZE7yAPLYVG]
