### ISSUE TITLE
Open an Account

### ISSUE THREAD

**Issue by samantha-kerr** [samantha-kerr/COMP353-MainProject#10]
- Client can open an account for different levels (personal, business, corporate) and types. 
- An Account Class needs to be created with Account attributes and functionality to add account record to the database. 
- An account creation form is needed with all options. 

### Constraints
- Credit Card accounts can only be created if there is at least 6 months of banking transactions in checking/savings account. 
- Line of Credit accounts can only be created if there is at least 1 year of banking transactions in checking/savings account. 

### Steps
- [x] Account class (model)
- [x]  Classes for all types of accounts (model)
- [x] Function for inserting  new account to DB (controller; can keep this in Account class)
- [x] Account creation form (view).

**Comment by jaslatendresse** [comment]
So far, there is a (very) basic UI where the view changes dynamically with the user's choices. 

There is a form validation function that handles whether or not the account can be created (credit if joining date >= 6 months, line of credit if joining date >= 12 months). This is tested with hard-coded values. 

We still need to retrieve the user data with $SESSION so it is fully functional with our DB. For now, all is working with hard-coded values and insertions are being made to DB.
