### ISSUE TITLE
List Client Accounts 

### ISSUE THREAD

**Issue by samantha-kerr** [samantha-kerr/COMP353-MainProject#9]
### Depends on #10 

- Client can view a list of their accounts of different categories with the current balance. 
- Clicking on the account will allow them to view the account details (#8).
- This view should be the home page when a Client logs in. 

### Steps
- [x] Function for retrieving a client's account from DB (controller; can keep this in Account class)
- [x] Show client accounts in tables; one table per account type (view)
- [ ] Add a button linking to account creation for each type (Open Account, Apply for Loan, etc.)

**Comment by jaslatendresse** [comment]
I think that the last task won't work because how I designed the thing for creating an account, it changes dynamically with what you select. I think we should drop it?

**Comment by samantha-kerr** [comment]
I’m not sure I understand... are you
not storing the account type name when you create the account? We should be able to easily query accounts of a client by type

**Comment by jaslatendresse** [comment]
yes we are, what i mean is that the form is the same and the elements change as you select the account type...so pressing a button to create one type of account only would be difficult with the design we currently have

**Comment by samantha-kerr** [comment]
Either clicking the button would preselect the account type in the form, or just make 1 button.
